[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'secretdev-1'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
event_source = { mode = 'push', url = 'ws://localhost:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'secret'
key_name = 'a'
store_prefix = 'ibc'
default_gas = 50000
max_gas = 2000000
gas_price = { price = 1, denom = 'uscrt' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '79s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [['wasm.*', '*'], ['transfer', '*']]

[[chains]]
id = 'secretdev-2'
rpc_addr = 'http://localhost:36657'
grpc_addr = 'http://localhost:9390'
event_source = { mode = 'push', url = 'ws://localhost:36657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'secret'
key_name = 'a'
store_prefix = 'ibc'
default_gas = 50000
max_gas = 2000000
gas_price = { price = 1, denom = 'uscrt' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '79s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [['wasm.*', '*'], ['transfer', '*']]
