[global]
add_to_hermes = false
auto_maintain_config = true
extra_wallets = 2
gaiad_binary = "$HOME/wasmd/build/wasmd"
hdpath = ""
home_dir = "$HOME/.gm"
ports_start_at = 27000
validator_mnemonic = ""
wallet_mnemonic = ""

[global.hermes]
binary = "$HOME/.hermes/hermes"
config = "$HOME/.hermes/config.toml"
log_level = "info"
telemetry_enabled = true
telemetry_host = "127.0.0.1"
telemetry_port = 3001

[pulsar-3]
ports_start_at = 27010

[uni-6]
ports_start_at = 27020

[node-0]
add_to_hermes = true
network = "pulsar-3"
ports_start_at = 27030

[node-1]
add_to_hermes = true
network = "uni-6"
ports_start_at = 27040
